title: DANIAL ASYRAFF
#logo: "" # Photo or logo

description: >
  Recent Computer Science graduate with a strong foundation in software engineering principles and a passion for learning new technologies. Experienced in graphic design, video editing, and project management, showcasing adaptability and a diverse skill set. Successfully completed a 3-month research internship under Dr. Dahlia Putri Dahnil binti Sikumbang, gaining valuable technical and research experience. Committed to delivering high-quality work and contributing to innovative solutions.
  <br><br>
  Second description
  <br><br>
  <a href="https://www.linkedin.com/in/danialasyraff">View My LinkedIn Profile</a>
  <br><br>

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

google_analytics:G-03GRFJJSNQ



